[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "clerk-backend-api>=1.1.0",
    "fastapi>=0.116.1",
    "openai>=1.99.9",
    "python-dotenv>=1.0.1",
    "sqlalchemy>=2.0.43",
    "uvicorn>=0.30.0",
    "pydantic>=2.7,<3",
    "svix>=1.74.1",
]
